config/routes.rb
Rbd::Application.routes.draw do
  resources :relatives, :except => [:edit, :update]
  resources :tenants, :except => [:edit, :update]
  resources :house_owners, :except => [:edit, :update]
  resources :plot_owners, :except => [:edit, :update]
  resources :owners, :only => [:show, :index]
  resources :members, :only => [:show, :index]

  resources :plots
  resources :houses
  resources :users

  %w[home location].each do |page|
    get page, controller: "pages", action: page
  end

  resources :sessions
  root to: 'pages#home'

end

app/models/owner.rb
class Owner < Member
end
require_dependency "plot_owner"
require_dependency "house_owner"

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  helper_method :sort_column, :sort_direction

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.order(sort_column + " " + sort_direction)
    @owners.count
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
    @owner = Owner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @owner }
    end
  end
  private
  def sort_column
    columns = Owner.column_names
    columns.include?(params[:sort]) ? params[:sort]: 'email'
  end

  def sort_direction
    %w[asc, desc].include?(params[:sort_dir]) ? params[:sort_dir]: 'asc'
  end
end

app/views/owners/index.html.erb
<h1><%= "All #{@owners.count} Owners" %></h1><br/>
<table id = "owners" class = "index">
  <thead>
  <tr>
    <th><%= sortable_link_to "name", "Name" %></th>
    <th><%= sortable_link_to "email", "Email ID" %></th>

    <th><%= sortable_link_to "phase", "Phase #" %></th>
    <th><%= sortable_link_to "plot_number", "Plot #" %></th>
    <th><%= sortable_link_to "plot_status", "Plot Status" %></th>
    <th><%= sortable_link_to "plot_area", "Area" %></th>

    <th><%= sortable_link_to "type", "Member Type" %></th>

    <th><%= sortable_link_to "house_number", "House #" %></th>
    <th><%= sortable_link_to "house_status", "House Status" %></th>
    <th><%= sortable_link_to "rwh", "rwh" %></th>
    <th><%= sortable_link_to "house_area", "Built Area" %></th>

  </tr>
  </thead>
  <tbody>
  <% @owners.each do |owner| %>
    <% present owner do |owner_presenter| %>
      <tr>
        <td><%=owner_presenter.name%></td>
        <td><%=owner_presenter.email%></td>

        <td><%=owner.phase%></td>
        <td><%=owner_presenter.plot_number%></td>
        <td><%=owner_presenter.plot_status%></td>
        <td><%=owner.plot_area%></td>

        <td><%=owner.type%></td>

        <td><%=owner_presenter.house_number%></td>
        <td><%=owner_presenter.house_status%></td>
        <td><%=owner_presenter.rwh%></td>
        <td><%=owner.house_area%></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/owners/show.html.erb
<% present @owner do |owner_presenter| %>
<h2><%= "Details for Owner #{@owner.email}" %></h2><br/>
  <ul class="show_fields">
    <li><label>Name: </label><span><%= @owner.name %></span></li>
    <li><label>Email: </label><span><%= @owner.email %></span></li>
    <li><label>Type: </label><span><%= @owner.type %></span></li>
    <br/>
    <li><label>Phase #: </label><%= @owner.phase %></li>
    <li><label>Plot #: </label><%= @owner.plot_number %></li>
    <li><label>Plot Status: </label><%=@owner.plot_status%></li>
    <li><label>Plot Area: </label><%=@owner.plot_area%></li>
  </ul><br/>

  <ul class = "show_links">
    <li><%= link_to 'Back to Owner list', owners_path %></li>
  </ul>
<% end %>