config/routes.rb
Rbd::Application.routes.draw do
  resources :relatives, :except => [:edit, :update]
  resources :tenants, :except => [:edit, :update]
  resources :house_owners, :except => [:edit, :update]
  resources :plot_owners, :except => [:edit, :update]
  resources :owners, :only => [:show, :index]
  resources :members, :only => [:show, :index]

  resources :plots
  resources :houses
  resources :users

  %w[home location].each do |page|
    get page, controller: "pages", action: page
  end

  resources :sessions
  root to: 'pages#home'

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  helper_method :sort_column, :sort_direction

  def new
    @house = House.new
  end

  def create
    house = params[:house]
    plot_number = house[:plot_number]
    @plot = Plot.find_by_number(plot_number)
    if !@plot
      flash[:alert] = "House::Create - Error: Plot #: #{plot_number} could not be found"
      @house = House.new
      render 'new' and return
    end
    @house = House.new(house)
    @house.plot_id = @plot.id
    if !@house.save
      flash[:alert] = "House::Create: Error - House # #{house[:number]}."
      @house = House.new
      render 'new' and return
    end

    flash[:notice] = "Created House # #{@house.number}."
    redirect_to houses_url
  end

  def index
    @houses = House.order(sort_column + " " + sort_direction)
  end

  def show
    @house = House.find(params[:id])
  end

  def edit
    @house = House.find params[:id]
  end

  def update
    @house = House.find params[:id]
    @house.update_attributes!(params[:house])
    flash[:notice] = "House # #{@house.number} was successfully updated."
    redirect_to house_path(@house)
  end

  def destroy
    @house = House.find(params[:id])
    @house.destroy
    flash[:notice] = "House '#{@house.number}' deleted."
    redirect_to houses_path
  end

  private
  def sort_column
    columns = House.column_names
    columns.include?(params[:sort]) ? params[:sort]: "number"
  end

  def sort_direction
    %w[asc, desc].include?(params[:sort_dir]) ? params[:sort_dir]: "asc"
  end
end

app/views/houses/edit.html.erb
<h1><%= "Edit House # #{@house.number}"  %></h1>
<br/>
<%= semantic_form_for @house, :url => {:action => "update"}, validate: true do |f| %>
  <%= render :partial => 'houses/shared/new_edit', locals: {f: f} %>
<% end %>

app/views/houses/index.html.erb
<h1><%= "All #{@houses.count} Houses" %> </h1><br/>
<%= link_to 'Add new house', new_house_path %><br/><br/>
<table id = "houses" class = "index">
  <thead>
  <tr>
    <th><%= sortable_link_to "phase", "Phase #" %></th>
    <th><%= sortable_link_to "plot_number", "Plot #" %></th>
    <th><%= sortable_link_to "number", "House #" %></th>
    <th><%= sortable_link_to "status", "Status" %></th>
    <th><%= sortable_link_to "area", "Built Area" %></th>
    <th><%= sortable_link_to "rwh", "rwh" %></th>
    <th/>
    <th/>
  </tr>
  </thead>
  <tbody>
  <% @houses.each do |house| %>
    <% present house do |house_presenter| %>
      <tr>
        <td><%=house_presenter.phase%></td>
        <td><%=house.plot_number%></td>
        <td><%=house.number%></td>
        <td><%=house_presenter.status%></td>
        <td><%=house.area%></td>
        <td><%=house_presenter.rwh%></td>
        <td><%= link_to "Show", house_path(house) %><span> | </span>
          <%= link_to "Edit", edit_house_path(house) %></td>
        <td><%= button_to 'Delete', house_path(house), :method => :delete, :confirm => 'Are you sure?' %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/houses/new.html.erb
<h1>Create House record</h1>

<%= semantic_form_for @house, validate: true do |f| %>
  <%= render :partial => 'houses/shared/new_edit', locals: {f: f} %>
<% end %>

app/views/houses/show.html.erb
<% present @house do |house_presenter| %>
  <h2><%= "Details for House # #{@house.number}" %></h2><br/>

<ul class="show_fields">
    <li><label>Phase #: </label><span><%= house_presenter.phase %></span></li>
    <li><label>Plot #: </label><%= @house.plot_number %></li>
    <li><label>House #: </label><%= @house.number %></li>
    <li><label>Status: </label><%= house_presenter.status %></li>
    <li><label>Area: </label><%= @house.area %></li>
    <li><label>RWH : </label><%= house_presenter.rwh %></li>
</ul><br/>

<ul class = "show_links">
  <li><%= link_to "Edit House", edit_house_path(@house) %></li>
  <li><%= link_to 'Back to house list', houses_path %></li>
  <li><%= button_to 'Delete', house_path(@house), :method => :delete, :confirm => 'Are you sure?' %></li>
</ul>
<% end %>