config/routes.rb
Rbd::Application.routes.draw do
  resources :relatives, :except => [:edit, :update]
  resources :tenants, :except => [:edit, :update]
  resources :house_owners, :except => [:edit, :update]
  resources :plot_owners, :except => [:edit, :update]
  resources :owners, :only => [:show, :index]
  resources :members, :only => [:show, :index]

  resources :plots
  resources :houses
  resources :users

  %w[home location].each do |page|
    get page, controller: "pages", action: page
  end

  resources :sessions
  root to: 'pages#home'

end

app/models/relative.rb
class Relative < Member
  belongs_to :family, :polymorphic => true
  attr_accessor :member_type
  attr_accessible :member_type
  def Relative.member_types
    [ ["Plot Owner", 'PlotOwner'],
      ["House Owner", 'HouseOwner'],
      ["Tenant", 'Tenant'],
    ]
  end
end

app/controllers/relatives_controller.rb
require_relative 'helpers/members_helper'

class RelativesController < ApplicationController
  helper_method :sort_column, :sort_direction
  include MembersHelper

  def new
    @relative = Relative.new
  end

  def show
    @relative = Relative.find(params[:id])
  end

  def create
    member_type, email, plot_number, house_number = params[:relative][:member_type], params[:relative][:email], params[:relative][:plot_number], params[:relative][:house_number]
    relative = get_relative(email)
    if relative
      flash[:alert] = "Relative::Create: Error - Relative with email: #{email} already exists, Family of #{relative.family.email}"
      @relative = Relative.new
      render 'new' and return
    end
    user = User.find_by_email(email)
    plot = Plot.find_by_number(plot_number) if !plot_number.blank?
    house = House.find_by_number(house_number) if !house_number.blank?
    if !user || (!plot && !house)
      flash[:alert] = "Relative::Create: Error - Specified email/plot/house is invalid - #{email}, Plot: #{plot_number}, House: #{house_number}"
      @relative = Relative.new
      render 'new' and return
    end

    if plot && house
      flash[:alert] = "Relative::Create: Error - Cannot specify both Plot & House  - #{email}, Plot: #{plot_number}, House: #{house_number}"
      @relative = Relative.new
      render 'new' and return
    end

    if member_type == 'PlotOwner' && !plot ||
       member_type != 'PlotOwner' && !house
      flash[:alert] = "Relative::Create: Error - Need Plot # for PlotOwner and House # for HouseOwner/Tenant"
      @relative = Relative.new
      render 'new' and return
      end

    case member_type
      when 'PlotOwner'
        @relative = create_plot_owner_relative(user, plot)
      when 'HouseOwner'
        @relative = create_house_owner_relative(user, house)
      when 'Tenant'
        @relative = create_tenant_relative(user, house)
    end
    if !@relative
      flash[:alert] = "Relative::Create: Error - : #{relative} \n: #{user}\n: #{plot}\n: #{house}"
      @relative = Relative.new
      render "new" and return
    end

    flash[:notice] = "Created Relative of #{member_type} #{@relative.email}"
    # session[:user_id] = @user.id   # Login the user too
    redirect_to relatives_path
  end

  def index
    @relatives = Relative.order(sort_column + " " + sort_direction)
  end

  def destroy
    @relative = Relative.find(params[:id])
    flash[:notice] = "Relative '#{@relative.email}' deleted."
    @relative.destroy
    redirect_to relatives_path
  end

  private
  def sort_column
    columns = Relative.column_names
    columns.include?(params[:sort]) ? params[:sort]: "email"
  end

  def sort_direction
    %w[asc, desc].include?(params[:sort_dir]) ? params[:sort_dir]: "asc"
  end

end

app/views/relatives/index.html.erb
<h1><%= "All #{@relatives.count} Relatives" %></h1><br/>
<%= link_to 'Add new relative', new_relative_path %><br/><br/>
<table id = "relatives" class = "index">
  <thead>
  <tr>
    <th><%= sortable_link_to "name", "Name" %></th>
    <th><%= sortable_link_to "email", "Email ID" %></th>
    <th><%= sortable_link_to "family", "Family of" %></th>

    <th><%= sortable_link_to "phase", "Phase #" %></th>
    <th><%= sortable_link_to "plot_number", "Plot #" %></th>
    <th><%= sortable_link_to "plot_area", "Area" %></th>

    <th><%= sortable_link_to "house_number", "House #" %></th>
    <th><%= sortable_link_to "house_status", "House Status" %></th>
    <th><%= sortable_link_to "house_area", "Area" %></th>
    <th><%= sortable_link_to "rwh", "RWH" %></th>

    <th/>
  </tr>
  </thead>
  <tbody>
  <% @relatives.each do |relative| %>
      <% present relative do |relative_presenter| %>
          <tr>
            <td><%=relative_presenter.name%></td>
            <td><%=relative_presenter.email%></td>
            <td><%=relative_presenter.relative%></td>

            <td><%=relative.phase%></td>
            <td><%=relative_presenter.plot_number%></td>
            <td><%=relative.plot_area%></td>

            <td><%=relative_presenter.house_number%></td>
            <td><%=relative_presenter.house_status%></td>
            <td><%=relative.house_area%></td>
            <td><%=relative_presenter.rwh%></td>

            <td><%= button_to 'Delete', relative_path(relative), :method => :delete, :confirm => 'Are you sure?' %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/relatives/new.html.erb
<h1>Create Relative</h1>
<br/>
<%= semantic_form_for @relative, :validate => true  do |f| %>
  <br/>
  <%= render partial: 'relatives/shared/new_edit', locals: {f: f} %>
<% end %>

app/views/relatives/show.html.erb
<% present @house_owner do |house_owner_presenter| %>
  <h2><%= "Details for House Owner #{@house_owner.email}" %></h2><br/>
  <ul class="show_fields">
    <li><label>Name: </label><span><%= @house_owner.name %></span></li>
    <li><label>Email: </label><span><%= @house_owner.email %></span></li>
    <br/>
    <li><label>Phase #: </label><%= @house_owner.phase %></li>
    <li><label>Plot #: </label><%= house_owner_presenter.plot_number %></li>
    <li><label>Plot Status: </label><%=house_owner_presenter.plot_status%></li>
    <li><label>Plot Area: </label><%=@house_owner.plot_area%></li>

    <li><label>House #: </label><%= house_owner_presenter.house_number %></li>
    <li><label>House Status: </label><%=house_owner_presenter.house_status%></li>
    <li><label>House Area: </label><%=@house_owner.house_area%></li>
    <li><label>RWH #: </label><%= @house_owner.rwh %></li>
  </ul><br/>

  <ul class = "show_links">
    <li><%= link_to 'New House Owner', new_house_owner_path %></li>
    <li><%= link_to 'Back to House Owner list', house_owners_path %></li>
    <li><%= button_to 'Delete', house_owner_path(@house_owner), :method => :delete, :confirm => 'Are you sure?' %></li>
  </ul>
  <% end %>