config/routes.rb
Rbd::Application.routes.draw do
  resources :relatives, :except => [:edit, :update]
  resources :tenants, :except => [:edit, :update]
  resources :house_owners, :except => [:edit, :update]
  resources :plot_owners, :except => [:edit, :update]
  resources :owners, :only => [:show, :index]
  resources :members, :only => [:show, :index]

  resources :plots
  resources :houses
  resources :users

  %w[home location].each do |page|
    get page, controller: "pages", action: page
  end

  resources :sessions
  root to: 'pages#home'

end

app/models/plot_owner.rb
class PlotOwner < Owner
  has_many :relatives, :as => :family, :dependent => :destroy
  belongs_to :plot
end

app/controllers/plot_owners_controller.rb
require_relative 'helpers/members_helper'

class PlotOwnersController < ApplicationController
  helper_method :sort_column, :sort_direction
  include MembersHelper

  def new
    @plot_owner = PlotOwner.new
  end

  def show
    @plot_owner = PlotOwner.find(params[:id])
  end

  def create
    email, plot_number = params[:plot_owner][:email], params[:plot_owner][:plot_number]
    owner = get_plot_owner(plot_number)
    if owner
      flash[:alert] = "PlotOwner::Create: Error - #{email}. Plot Owner #{owner.email} already exists for #{plot_number}"
      @plot_owner = PlotOwner.new
      render 'new' and return
    end
    user = User.find_by_email(email)
    plot = Plot.find_by_number(plot_number)
    if !user || !plot
      flash[:alert] = "Create: Error - Specified email or plot # is invalid - #{email}, #{plot_number}"
      @plot_owner = PlotOwner.new
      render 'new' and return
    end

    @plot_owner = create_plot_owner(user, plot)
    flash[:notice] = "Created Plot Owner #{@plot_owner.email}"
    # session[:user_id] = @user.id   # Login the user too
    redirect_to plot_owners_path
  end

  def index
    @plot_owners = PlotOwner.order(sort_column + " " + sort_direction)
  end

  def destroy
    @plot_owner = PlotOwner.find(params[:id])
    flash[:notice] = "PlotOwner '#{@plot_owner.email}' deleted."
    @plot_owner.destroy
    redirect_to plot_owners_path
  end

  private
  def sort_column
    columns = PlotOwner.column_names
    columns.include?(params[:sort]) ? params[:sort]: "email"
  end

  def sort_direction
    %w[asc, desc].include?(params[:sort_dir]) ? params[:sort_dir]: "asc"
  end

  def current_resource
    @current_resource ||= PlotOwner.find(params[:id]) if params[:id]
  end
end

app/views/plot_owners/index.html.erb
<h1><%= "All #{@plot_owners.count} Plot Owners" %> </h1><br/>
<%= link_to 'Add new plot_owner', new_plot_owner_path %><br/><br/>
<table id = "plot_owners" class = "index">
  <thead>
  <tr>
    <th><%= sortable_link_to "name", "Name" %></th>
    <th><%= sortable_link_to "email", "Email ID" %></th>

    <th><%= sortable_link_to "phase", "Phase #" %></th>
    <th><%= sortable_link_to "plot_number", "Plot #" %></th>
    <th><%= sortable_link_to "plot_status", "Plot Status" %></th>
    <th><%= sortable_link_to "plot_area", "Area" %></th>

    <th/>
  </tr>
  </thead>
  <tbody>
  <% @plot_owners.each do |plot_owner| %>
      <% present plot_owner do |plot_owner_presenter| %>
          <tr>
            <td><%=plot_owner_presenter.name%></td>
            <td><%=plot_owner_presenter.email%></td>

            <td><%=plot_owner.phase%></td>
            <td><%=plot_owner_presenter.plot_number%></td>
            <td><%=plot_owner_presenter.plot_status%></td>
            <td><%=plot_owner.plot_area%></td>

            <td><%= button_to 'Delete', plot_owner_path(plot_owner), :method => :delete, :confirm => 'Are you sure?' %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/plot_owners/new.html.erb
<h1>Create Plot Owner</h1>
<br/>
<%= semantic_form_for @plot_owner, :validate => true  do |f| %>
  <br/>
  <%= render partial: 'plot_owners/shared/new_edit', locals: {f: f} %>
<% end %>

app/views/plot_owners/show.html.erb
<% present @plot_owner do |plot_owner_presenter| %>
  <h2><%= "Details for Plot Owner #{@plot_owner.email}" %></h2><br/>
  <ul class="show_fields">
    <li><label>Name: </label><span><%= @plot_owner.name %></span></li>
    <li><label>Email: </label><span><%= @plot_owner.email %></span></li>
    <br/>
    <li><label>Phase #: </label><%= @plot_owner.phase %></li>
    <li><label>Plot #: </label><%= plot_owner_presenter.plot_number %></li>
    <li><label>Plot Status: </label><%=plot_owner_presenter.plot_status%></li>
    <li><label>Plot Area: </label><%=@plot_owner.plot_area%></li>
  </ul><br/>

  <ul class = "show_links">
    <li><%= link_to 'New Plot Owner', new_plot_owner_path %></li>
    <li><%= link_to 'Back to Plot Owner list', plot_owners_path %></li>
    <li><%= button_to 'Delete', plot_owner_path(@plot_owner), :method => :delete, :confirm => 'Are you sure?' %></li>
  </ul>
  <% end %>